### ISSUE TITLE
Excessive syscall usage, uncached data?

### ISSUE THREAD

**Issue by mirschkyn** [kmod-project/kmod#11]
depmod (29) seems to do something out of the ordinary. This is with less than a handful of kernel modules.
Looks to me like it's re-reading the same data over and over again.
Unfortunately it leads to a very noticeable execution time using it during emulation due to the syscall heavy behavior.

$ strace -c depmod
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 98.79    0.640032           1    513930           pread64
  0.77    0.004959           0      7042           lseek
  0.21    0.001364           2       463           openat
  0.09    0.000551           1       463         4 newfstatat
  0.08    0.000537           1       463           close
  0.03    0.000171           0       413           read
  0.02    0.000139           1       131           write
  0.01    0.000039           3        10           renameat
  0.01    0.000034           0        64           getdents64
  0.00    0.000022           0        75           fcntl
  0.00    0.000011           5         2           munmap
  0.00    0.000010           0        25           brk
  0.00    0.000002           0        17           mmap
  0.00    0.000002           0        10           getpid
  0.00    0.000000           0         7           mprotect
  0.00    0.000000           0         1         1 access
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         1           uname
  0.00    0.000000           0         1           arch_prctl
  0.00    0.000000           0         1           set_tid_address
  0.00    0.000000           0         1           set_robust_list
  0.00    0.000000           0         1           prlimit64
  0.00    0.000000           0         1           getrandom
------ ----------- ----------- --------- --------- ----------------
100.00    0.647873           1    523123         5 total

**Comment by mirschkyn** [comment]
Suggested fix in series by Lucas:
https://lore.kernel.org/linux-modules/20220211084230.4489-1-lucas.demarchi@intel.com/

Works for me.

**Comment by lucasdemarchi** [comment]
@mirschkyn  I was trying to find the what was the speedup you had in the end, but the only numbers I kept in the commit message was when running depmod natively. Do you have an idea before/after what that was?

**Comment by mirschkyn** [comment]
@lucasdemarchi: Sorry for the late reply.
So. This is on an emulated arm. So machine is slow. Excessive syscall usage becomes really apparent.
This machine has a custom built rootfs, depmod stuck somewhere in the boot sequence.
The machine would "freeze" while processing the excessive syscalls from depmod.
before fix (vanilla 29).
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 99.32   32.541375         110    293336           pread64
  0.24    0.078231          73      1063           _llseek
  0.17    0.057135         182       313           openat
  0.10    0.034336         109       313           close
  0.10    0.034287         109       312         4 statx
  0.01    0.004245         202        21           write
  0.01    0.002974         297        10           renameat
  0.01    0.002387          72        33           read
  0.01    0.001831         130        14           mmap2
  0.01    0.001744        1744         1           execve
  0.00    0.001460          63        23           fcntl64
  0.00    0.000951          79        12           getdents64
  0.00    0.000641          64        10           getpid
  0.00    0.000454          56         8           mprotect
  0.00    0.000299          37         8           munmap
  0.00    0.000251          41         6           brk
  0.00    0.000067          67         1         1 access
  0.00    0.000041          41         1           set_tls
  0.00    0.000027          27         1           set_robust_list
  0.00    0.000026          26         1           set_tid_address
  0.00    0.000026          26         1           rseq
  0.00    0.000000           0         1           uname
  0.00    0.000000           0         1           mremap
  0.00    0.000000           0         1           ugetrlimit
  0.00    0.000000           0         1           getrandom
------ ----------- ----------- --------- --------- ----------------
100.00   32.762788         110    295492         5 total

after fix (pre-30):
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 63.27    0.046217          65       702           _llseek
  6.30    0.004601         148        31           openat
  4.36    0.003187         109        29         4 statx
  4.35    0.003174          70        45           read
  3.75    0.002738         273        10           renameat
  3.48    0.002542         141        18           write
  3.40    0.002480          80        31           close
  2.39    0.001744        1744         1           execve
  1.85    0.001352          56        24           fcntl64
  1.80    0.001316         109        12           getdents64
  1.78    0.001301          92        14           mmap2
  1.20    0.000880         110         8           munmap
  0.73    0.000535          53        10           getpid
  0.43    0.000315          39         8           mprotect
  0.32    0.000237          47         5           brk
  0.12    0.000091          91         1           mremap
  0.10    0.000072          72         1         1 access
  0.08    0.000059          59         1           ugetrlimit
  0.08    0.000058          58         1           set_robust_list
  0.06    0.000047          47         1           rseq
  0.04    0.000032          32         1           set_tls
  0.04    0.000027          27         1           getrandom
  0.03    0.000021          21         1           uname
  0.03    0.000020          20         1           set_tid_address
------ ----------- ----------- --------- --------- ----------------
100.00    0.073046          76       957         5 total

So even on this slow machine, syscall usage > 30 seconds down to 0.07 sec when straced.
Without strace things are obviously faster, but we're still talking walltime difference in the order of more than two magnitudes.
