### ISSUE TITLE
kmod-29

### ISSUE THREAD

**Issue by yodelu** [kmod-project/kmod#12]
Worked fine.. until this
https://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git/commit/?id=82972710196442c503cc1068a05651c354a865fb
and.. that is happening on latest commit too ( https://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git/commit/?id=94f7683c5a5084b61756c6df29c14041efebcd94 )
The problem: doing modprobe or modinfo on unexisting module throws kmod into a segfault..
modinfo blahblah
Segmentation fault
Any ideea ?

**Comment by lucasdemarchi** [comment]
Thanks for the bug report. Just pushed the fix to 571a84c9249257bf70f9111b30509aa121405cab

**Comment by yodelu** [comment]
now it works -:)
thx!
