### ISSUE TITLE
Add and use move overflow helpers

### ISSUE THREAD

**Issue by evelikov** [kmod-project/kmod#162]
@stoeckmann has been diligently going through the code base adding overflow checks. Overall it would be cleaner if we add new variants akin to `addu64_overflow` instead of having them open-coded.

Ideally we'll check and reuse compiler built-ins, where possible. They can be made mandatory with the impact clearly documented in the commit messages - which gcc/clang version introduced them, which distros use those as base.

See https://github.com/kmod-project/kmod/pull/149#issuecomment-2380395360 for some more context and examples.

**Comment by stoeckmann** [comment]
I think this issue is resolved, or do you expect to add more overflow helpers?
