### ISSUE TITLE
depmod: built-in module is updated into modules.dep instead of the duplicated one in "extra" dir

### ISSUE THREAD

**Issue by winndows** [kmod-project/kmod#17]
Hello,

As we know, module in "extra" has higher priority than the duplicate one in kernel.

But it looks like when we run depmod, inside it, the readdir() read sub-dirs of /lib/modules/5.18.0-0.bpo.1-rt-amd64/, it does not always read out "extra" before "kernel" and this makes ko path in built-in kernel is updated into modules.dep, but what we want is the path in "extra".

I was using isar: https://github.com/ilbers/isar to build a system img
and in the img, i have one ko as kernel built-in and a duplicated one in "extra"
before start the img, i chroot into the rootfs of the img on the build machine, but when I run "depmod -a $(ls /lib/modules/)", it will put built-in ko into modules.dep and I found readdir read kernel dir firstly instead of extra dir.

kernel is read firstly by readdir():
![image](https://user-images.githubusercontent.com/9544734/185874914-2f83917a-3649-484b-b14e-3f13ab46cf74.png)

![image](https://user-images.githubusercontent.com/9544734/185874582-e4791b46-f075-489d-9485-b35f2b9fa3be.png)

module in extra is set as lower prio:
![image](https://user-images.githubusercontent.com/9544734/185874754-4da8648b-29e4-498f-8a2f-d48574b30421.png)

**Comment by lucasdemarchi** [comment]
built-in is always highest prio as it means the module is in the kernel image rather than being built as a module. You can't override that with a module. If you need that, you need to change your kernel config to make that kconfig entry a module.

**Comment by lucasdemarchi** [comment]
Although from your logs it's actually using a module. Did you mix the built-in index with another kernel or is just the word used the threw me off?

**Comment by lucasdemarchi** [comment]
From your logs I also see you don't have any depmod.d. A config in one of these directories is where depmod learns the search priority from so you probably need to add one such file

**Comment by winndows** [comment]
> built-in is always highest prio as it means the module is in the kernel image rather than being built as a module. You can't override that with a module. If you need that, you need to change your kernel config to make that kconfig entry a module.

sorry, "built-in" I mean the module is built with kernel and installed in the /lib/modules/`uname -r`/kernel/, but it is a module, not in the vmlinuz img.  "extra" means modules are installed in the /lib/modules/`uname -r`/extra/

**Comment by winndows** [comment]
> From your logs I also see you don't have any depmod.d. A config in one of these directories is where depmod learns the search priority from so you probably need to add one such file

I have another system(vmware vm using the img  I built), instead of the one I mentioned before(rootfs of isar img), when I do depmod, the readdir will always read extra firstly, then ko in extra path will updated to modules.dep.

Yes, I don't have any depmod.d for both of them. adding such a file can be a workaround, but I hope you expert could help to find the root cause.


![image](https://user-images.githubusercontent.com/9544734/186056095-0f27d87f-5bea-4427-ba0b-78cd88beccbb.png)

![image](https://user-images.githubusercontent.com/9544734/186056030-b8ca0254-63f5-4df8-b4a1-5f445ece2376.png)

**Comment by winndows** [comment]
Currently, the situation is:

1. in chroot env of img rootfs, run depmod, readdir will read "kernel" firstly, then update ko in kernel dir to modules.dep
2. in vm or real HW, run depmod, readdir will read "extra" firstly, then update ko in extra dir to modules.dep

So I suspect "readdir" is not trustable here.

**Comment by lucasdemarchi** [comment]
you can't rely on readdir order. If you don't set a search order to change the priorities of each of the directories, they will have the same priority and any of them will be picked up.

There is one exception: if there's no configuration the default is to use the order "updates built-in". If you don't want the configuration file, then I suggest using that name.

```
           By default, depmod will give a higher priority to a directory with
           the name updates using this built-in search string: "updates
           built-in" but more complex arrangements are possible and are used
           in several popular distributions.
```

This is what Manjaro has:

```
$ cat /usr/lib/depmod.d/search.conf 
#
# /usr/lib/depmod.d/search.conf
#

search updates extramodules built-in
```

And Ubuntu:

```
$ cat /etc/depmod.d/ubuntu.conf 
search updates ubuntu built-in
```

**Comment by winndows** [comment]
Thanks a lot for the info.

One more concern, what does the "built-in" mean in the following?
`$ cat /etc/depmod.d/ubuntu.conf 
search updates ubuntu built-in`

I was thinking that modules whose code is with kernel are called built-in: no matter if they are built out in vmlinux or a separated moudule in /lib/modules/`uname -r`/kernel.

**Comment by winndows** [comment]
Thanks a lot.
