### ISSUE TITLE
Queried values not returned

### ISSUE THREAD

**Issue by Ricky-Tigg** [kmod-project/kmod#22]
kmov v.: 30
```
$ lsmod | grep -w ^tls
tls                   126976  0
```
Hello. Queried values are here returned. Nevertheless i am not competent to determine whether they are expected since i note that i am currently not in a **script file**.
```
# modinfo -l tls
Dual BSD/GPL
# modinfo -d tls
Transport Layer Security Support
```
This command still observes the previous semantic; which leads to expect that queried values are to be returned; as noticeable that is not the case.
```
# modinfo -d -l tls
Dual BSD/GPL
```
It might be the indication of an issue. Expected was
```
Transport Layer Security Support
Dual BSD/GPL
```

**Comment by lucasdemarchi** [comment]
it's only one filter flag that is taken in consideration. -d and -l are only considered as shortcuts to the longer --field=description and and --field=license

That said, we could allow multiple options to "accumulate".
