### ISSUE TITLE
usb:btusb's problem

### ISSUE THREAD

**Issue by larryonly** [kmod-project/kmod#5]
I have a question for kmod.
There is a soft connection file usb:btusb existing in kmod/testsuite/rootfs-pristine/test-loaded/sys/module/btusb, Who’s link object of the file is empty.
The testsuite file does not affect the main functions. But I want to make sure whether it is a problem.

Thanks!

**Comment by lucasdemarchi** [comment]
Sorry for the delay, I didn't have notification in github setup properly for kmod. That is harmless. It's just and easy way to get tests added. The test won't rely on that file for what it's checking.
